name: Module test
on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
