name: Module Resource Group

  push:
    paths:
      - resource-group/**

jobs:
  static_analysis:
    uses: ./.github/workflows/static-analysis.yaml
    with:
      module: resource-group
      terraform_version: 1.3.6