name: Static Analysis

on:
  workflow_call:
    inputs:
      module:
        type: string
        required: true
      terraform_version:
        type: string
        required: true

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Go to module root
      run: cd ${{ inputs.module }}
    - name: Display contents
      run: ls
    - name: Black
      uses: psf/black@stable
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check